### PR TITLE
Fix SSE4 feature flag names

### PR DESCRIPTION
**Pull request by marquiz**
Fixes an API breakage caused by
43f4c41326096a3d90b250136a41d7e0c46bbcd8.

### CODE REVIEW

**Comment by klauspost** [comment]
@marquiz Could you be a bit more specific about what it fixes?

**Comment by marquiz** [comment]
> Could you be a bit more specific about what it fixes?

`SSE4.1` was renamed to `SSE4` and `SSE4.2` was renamed to `SSE42`. I just see this as an unnecessary API breakage. This patch changes the names back to how they were in v1.

**Comment by klauspost** [comment]
Well, for v1 -> v2 changes like this can be expected. Changing it now would be a breaking change, so not a huge fan of it, even if I agree it is nicer.

Thinking a bit about it.

**Comment by marquiz** [comment]
> Well, for v1 -> v2 changes like this can be expected. Changing it now would be a breaking change, so not a huge fan of it, even if I agree it is nicer.

Yeah, unofrtunately I didn't spot this until now, as I think it was a totally unnecessary API breakage

**Pull request closed without merging**
