### PR TITLE
strip trailing zero from brand name

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by klauspost** [comment]
Thanks for reporting this!

The bug is in `valAsString`, where the switch is on `r` instead of `dst`.

The switch should be:
```
		switch {
		case dst[0] == 0:
			return r[:i*4]
		case dst[1] == 0:
			return r[:i*4+1]
		case dst[2] == 0:
			return r[:i*4+2]
		case dst[3] == 0:
			return r[:i*4+3]
		}
```
You are welcome to change your PR, or I can submit it if you'd like.

**Comment by ebfe** [comment]
On Wed, Jun 24, 2015 at 05:20:56AM -0700, Klaus Post wrote:
> The bug is in `valAsString`, where the switch is on `r` instead of `dst`.

Sorry, I didn't even look at this function.

Updated.

On a second thought. Do all cpus pad the string with spaces to 47 chars?
Otherwise appending to name should probably stop after seeing the first
0. (disclaimer: I didn't read any spec in detail).

**Comment by klauspost** [comment]
>Otherwise appending to name should probably stop after seeing the first 0.

This is what 'valAsString' was intended to do.  It is a maximum 48 byte zero-terminated string.

**Comment by ebfe** [comment]
On Wed, Jun 24, 2015 at 05:42:05AM -0700, Klaus Post wrote:
> >Otherwise appending to name should probably stop after seeing the first 0.
> 
> This is what 'valAsString' was intended to do.  It is a maximum 48 byte zero-terminated string.

So the loop in cpuid.go:542 should terminate early if any zero is detected. 

    0x41414141, 0x41414141, 0x41414141, 0x00414141 = cpuid(0x80000002)
    0x42424242, 0x42424242, 0x42424242, 0x00424242 = cpuid(0x80000003)
    0x43434343, 0x43434343, 0x43434343, 0x00434343 = cpuid(0x80000004)

should result in "AAAAAAAAAAAAAAA" but it would result in 
"AAAAAAAAAAAAAAABBBBBBBBBBBBBBBCCCCCCCCCCCCCCC" right now.

**Comment by klauspost** [comment]
@ebfe - you are of course right!  Thanks again!

**Pull request merged**
